[theme]
primaryColor = "#0496FF"
backgroundColor = "#FFFFFF" 
secondaryBackgroundColor = "#F0F2F6"
textColor = "#333333"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[ui]
hideTopBar = true
hideSidebarNav = false